<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterIdDetalja/AdapterIdDetalja/GetIdDetalja" name="GetIdDetalja-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterIdDetalja/AdapterIdDetalja/GetIdDetalja" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterIdDetalja/AdapterIdDetalja/GetIdDetalja" location="../adapter/AdapterIdDetalja/GetIdDetalja.wsdl"/>
  <binding name="GetIdDetalja_ptt-binding" type="tns:GetIdDetalja_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="GetIdDetaljaSelect">
      <soap:operation soapAction="GetIdDetaljaSelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GetIdDetalja-service">
    <port name="GetIdDetalja-port" binding="tns:GetIdDetalja_ptt-binding">
      <soap:address location="jca://eis/DB/EtpmTest"/>
    </port>
  </service>
</definitions>