<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/UverenjaZaIzvrsiteljeReport/UverenjaZaIzvrsiteljeReport/PregledZahtevaIzvrsitelja" name="PregledZahtevaIzvrsitelja-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/UverenjaZaIzvrsiteljeReport/UverenjaZaIzvrsiteljeReport/PregledZahtevaIzvrsitelja" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UverenjaZaIzvrsiteljeReport/UverenjaZaIzvrsiteljeReport/PregledZahtevaIzvrsitelja" location="../adapter/UverenjaZaIzvrsiteljeReport/PregledZahtevaIzvrsitelja.wsdl"/>
  <binding name="PregledZahtevaIzvrsitelja_ptt-binding" type="tns:PregledZahtevaIzvrsitelja_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="PregledZahtevaIzvrsiteljaSelect">
      <soap:operation soapAction="PregledZahtevaIzvrsiteljaSelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="PregledZahtevaIzvrsitelja-service">
    <port name="PregledZahtevaIzvrsitelja-port" binding="tns:PregledZahtevaIzvrsitelja_ptt-binding">
      <soap:address location="jca://eis/db/EtpmTest"/>
    </port>
  </service>
</definitions>