<?binding.jca GetIdDetalja_db.jca?>
<wsdl:definitions name="GetIdDetalja" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterIdDetalja/AdapterIdDetalja/GetIdDetalja" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterIdDetalja/AdapterIdDetalja/GetIdDetalja" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetIdDetalja">
    <plt:partnerLinkType name="GetIdDetalja_plt">
        <plt:role name="GetIdDetalja_role">
            <plt:portType name="tns:GetIdDetalja_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetIdDetalja" schemaLocation="xsd/GetIdDetalja_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetIdDetaljaSelect_inputParameters">
        <wsdl:part name="GetIdDetaljaSelect_inputParameters" element="top:GetIdDetaljaSelect_idDetaljaInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CmZahtevUverenjeCollection_msg">
        <wsdl:part name="CmZahtevUverenjeCollection" element="top:CmZahtevUverenjeCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetIdDetalja_ptt">
        <wsdl:operation name="GetIdDetaljaSelect">
            <wsdl:input message="tns:GetIdDetaljaSelect_inputParameters"/>
            <wsdl:output message="tns:CmZahtevUverenjeCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
